# @package _global_
defaults:
  - ../default

task_name: clean_dining_table
checkpoint: ./checkpoints/DM0-table30_clean_dining_table
action_horizon: 15

postprocess_args:
  gripper_threshold: 0.02
  gripper_open: null
  gripper_close: 0.0
