# @package _global_
defaults:
  - ../default

task_name: hang_toothbrush_cup
checkpoint: ./checkpoints/DM0-table30_hang_toothbrush_cup
action_horizon: 10

postprocess_args:
  gripper_threshold: 50
  gripper_open: 228
  gripper_close: 3
