# @package _global_
defaults:
  - ../default

task_name: move_objects_into_box
checkpoint: ./checkpoints/DM0-table30_move_objects_into_box
action_horizon: 25
duration: 0.185

postprocess_args:
  gripper_threshold: 0.04
  gripper_open: 0.084
  gripper_close: 0.004
