# @package _global_
defaults:
  - ../default

task_name: sort_books
checkpoint: ./checkpoints/DM0-table30_sort_books
action_horizon: 15

postprocess_args:
  gripper_threshold: 50
  gripper_open: 228
  gripper_close: 3
