# @package _global_
defaults:
  - ../default

task_name: sweep_the_rubbish
checkpoint: ./checkpoints/DM0-table30_sweep_the_rubbish
action_horizon: 25

postprocess_args:
  gripper_threshold: 0.035
  gripper_open: null
  gripper_close: 0.0
