# @package _global_
defaults:
  - ../default

task_name: put_opener_in_drawer
checkpoint: ./checkpoints/DM0-table30_generalist_aloha
action_horizon: 35

postprocess_args:
  gripper_threshold: 0.03
  gripper_open: null
  gripper_close: 0.0
