# @package _global_
defaults:
  - ../default

task_name: set_the_plates
checkpoint: ./checkpoints/DM0-table30_generalist_ur5
action_horizon: 15

postprocess_args:
  gripper_threshold: 50
  gripper_open: 228
  gripper_close: 3
