# @package _global_
defaults:
  - ../default

task_name: stick_tape_to_box
checkpoint: ./checkpoints/DM0-table30_generalist_aloha
action_horizon: 15

postprocess_args:
  gripper_threshold: 0.003
  gripper_open: null
  gripper_close: 0.0
